apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgBi48B+MRcCRVWVwDrlGirzuGLe/+iu8mD84ymGl0vzIZKjWnuZ/yGD2mCPGtIwhMnFBm0uQR+32EzYF2uwMycvn0cppgkPfdMuD2zFMzXU8FR73uSuvSbYccBNBVOhlLLMuvW7wS0Go0b4cD8K3KQs4Z24Hu+Jb+uzIqHE7B70t7s2VqgzVhkJSMy7zBlZrsBT7eXPY3NDLXc5HqA4J47mNrGZbGkQAMd4mvatIHltemRZg3O9GGQb6BvpcExbm6NPWZvgiAsFBOA8P356B1fYdR9FKedkFuOHhHfSxmEVUXLSmK6DdO7HOpC0E4YsVD5GUGfZgyPuNxeiwzXJKDmraOIQnd13lmZ3C5mIVkd5bQZe856QJwq4uDxC/5Rq8UJzAmNXHIX8eP3Z80M0ZaUCBqkWchBihzu4qBwHafY6TNsQKDQ2cU6LcjTDc0g82WCckS32VNK4Ll+PwXG5P+nLxBMsmzmglEY+v4ugJPaX2jP70cYCdgMDQg+MkwprE7v/XgP0AfW6Ez9QFImehkdfmqCxROnT0VW2UCdv9OigjhfI9oYJxcFUgAlDQuTxD5ZmWGCJ1El4Zt9Ny96NUOECb/qTEM+pMpU1vNxc9jfrwRh2LgBVDWmELQyJVLZf+0TzHjBx4N1ZQ2dDTBVurDcmij2zWsITV681JDuRuU3AihhJDfQfnD9qNqhTKZOozRMKLIkhLnuyY1dhFxEi+QgsBYYk7dsxRhZGQTNwy6grBNrsVjQ5iEBbjsJem4BCbuY0JxWg0AikwqbSoQlnyQtuAq/BOjYdY/UYAJOemVRoP5c7SKHJoAMBAx+GbP6Ti22k+AtR0v7aNDAO8l/w3XChlLhLWQ4=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

