apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgB0TJqd94k/S9mol+OIE/gtyesfQNUNDpGS6m0G/BvsQ6qPEpl7k7RkCSPxJ8Mwqq52iw7oAe8dhIO2bGclaYOfC/4L75YgYMLjmDblvOFU4I5J/VLSW/WwEtazJ3l6JqWp1ieba1Z3iEov6qggIOFW7YrPp4tj9h6dagAu6pWb5ma68hsmODRAgzu09nFveEF6baFb/1eKeu2cuqS5kXmDyhhY+4YmLU3tGYG996X5zX2nT5JSflo2eFzGfOhzHABgCv1qClcC8C6CJQxhL/VSGY8Ul5qqQi+TzRhoOPlrvCCr8g0zvY6xMPWN1x0GNNMVX3dufkfzM1AyUcRnHTyf+3TMeIZIxLNQ+qXi2ZaTxTagwh7bRKWMKawQ2iwmbAPdr15ajd6Egae6uAR6YBmnKKdKmdFvshj2qInziVGF31zCOVXwHgoSAufvOUm7oJcja7rVGamhVRWKJwWgCPEmipM40qMzVlcfT47ZaSD7BpnLHDGnbcVPPM/UwfvlCbOJBFM6vEnyDb1v1u41KiuWKGVgMvwaTH+sFLHZRgs1wQkrV6JlSTPxlxxPOoPMD/0+BYjqVXPkXbDT+EraU/gcX38ljxxpxHJCddatK9MY6XOla8i0QJkzfCyrCRBYZwAH+nClwNr9R5QT8kn5/DDGyrW/+sVFii+EmWA7qg9Bt7aL7xXAOHyUvNEYGIgZ1TYiAV6EbYwi5jddIsaf7JrLlZKr1w3W2ODsSIi2g2xGj4ljyavrcT4AFH+yHaZ4UoPHtctqrQlTN8LmVplR2/GRr4dnxGLviN2DJ1K1gyvFf+AQjnFg3AmQehgCXHEptdvHupp90+XU0VDvOW5GP2PzEBvtX34=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

