apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-a-apps-reqs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: team-app-reqs
    repoURL: https://github.com/matt-kg/crossplane-kubevela-argocd-demo
    targetRevision: HEAD
  destination:
    server: https://2584D69797724D9BEB5B907820D962C3.gr7.us-west-2.eks.amazonaws.com
    namespace: production
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
